### ISSUE TITLE
W3C

### ISSUE THREAD

**Issue by GgLaPoule** [cdmcruises/MyPlace-Discovery#2]
1 Line 36, Column 44: An img element must have an alt attribute, except under certain conditions. For details, consult guidance on providing text alternatives for images.
		```<div id="logo"><img src="./img/Logo.jpg"/> </div>```

2  Line 38, Column 5: Element li not allowed as child of element nav in this context. (Suppressing further errors from this subtree.)
	```<li><a href="/home">Accueil</a></li>```

3 Line 39, Column 5: Element li not allowed as child of element nav in this context. (Suppressing further errors from this subtree.)
```<li><a onclick="javascript:afficher_cacher('login_box')" style="cursor: pointe..
<li><a href="/sign_up">Inscription</a></li>	</nav>```

4 Line 73, Column 34: Duplicate ID game.
			```<div id="game" class="accueil">```
 Line 45, Column 17: The first occurrence of ID game was here.
		```<div id="game">```

**Comment by cdmcruises** [comment]
Merci d'encadrer tout le menu avec un 
```html
<ul></ul>
Merci de corriger le alt de l'image
je me charge du doublon d'id.

**Comment by cdmcruises** [comment]
@GgLaPoule : Le <ul> a créé un formatage de liste à puce.

**Comment by cdmcruises** [comment]
@GgLaPoule a ajouté le ul et le alt (1 - 2 - 3 corrigés)
Nouveau bug : Apparition de puces.
@cdmcruises (moi) : J'ai corrigé le bug des puces et supprimé le doublons d'id. Propriété list-style de nav supprimée, car inutile.
Document passé au validateur HTML5.
Fermeture du bug.
