### ISSUE TITLE
Problème de traitement des données

### ISSUE THREAD

**Issue by GgLaPoule** [cdmcruises/MyPlace-Discovery#3]
La réponse "La mangue" n'est pas valide tandis que "la mangue" l'est.
Ne pas respecter la casse résoudrait ce problème.
Envoyer un formulaire vide valide la réponse, le traitement des réponses est à revoir.

**Comment by cdmcruises** [comment]
Bug corrigé. Ajout de mb_strtolower en UTF-8.
