### ISSUE TITLE
Margin niveaux

### ISSUE THREAD

**Issue by GgLaPoule** [cdmcruises/MyPlace-Discovery#6]
Les niveaux sur la deuxième ligne dans .game restent collés aux niveaux de la première ligne.
L'ajout d'un margin qui s'appliquerait sur les 3 derniers niveaux résoudrait le problème

**Comment by GgLaPoule** [comment]
J'ai résolu le bug en mettant un margin 70px sur tous les blocs niveaux, mais si il y a possibilité de faire une condition php pour le faire uniquement sur les 3 derniers niveau cela serait plus "controlé".

**Comment by cdmcruises** [comment]
Je pense que ce que tu veux, c'est plutôt que la propriété ne s'applique pas aux 3 premiers ?

**Comment by GgLaPoule** [comment]
Oui voilà.

**Comment by cdmcruises** [comment]
problème réglé ;)
